### ISSUE TITLE
Remove changing backround color for compatibility with OpenMonitors and CorporateRestructure

### ISSUE THREAD

**Issue by Janonas** [cdusold/lethal-comptime#2]
When using this mod with OpenMonitors or CorporateRestructure, the game will disconnect any player that tries to join your hosted game. Repeated testing shows that this is a problem with the feature that changes the monitors backround color, as the afformentioned mods remove the blue rectangle and just use the monitors as background. It would be nice to be able to use these mods together.

**Comment by cdusold** [comment]
Can you try v1.0.1? @Janonas
